// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnIcC7gicqfu4A0sBIm89ghyk8Pk0FwAQ',
    appId: '1:191554436392:web:c7b63ffe1e96d35054641d',
    messagingSenderId: '191554436392',
    projectId: 'import-mark',
    authDomain: 'import-mark.firebaseapp.com',
    storageBucket: 'import-mark.appspot.com',
    measurementId: 'G-954ZN7SWBT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBzQPRp5opHP_CHkAizZZnJy1brAfrwaU',
    appId: '1:191554436392:android:e84afc21cf90b58854641d',
    messagingSenderId: '191554436392',
    projectId: 'import-mark',
    storageBucket: 'import-mark.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBxWnY-hRZCEQtftBgKAQyLMvrHTthCB4',
    appId: '1:191554436392:ios:e4e943469afa221454641d',
    messagingSenderId: '191554436392',
    projectId: 'import-mark',
    storageBucket: 'import-mark.appspot.com',
    iosBundleId: 'com.mosharof.importMark',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBxWnY-hRZCEQtftBgKAQyLMvrHTthCB4',
    appId: '1:191554436392:ios:e4e943469afa221454641d',
    messagingSenderId: '191554436392',
    projectId: 'import-mark',
    storageBucket: 'import-mark.appspot.com',
    iosBundleId: 'com.mosharof.importMark',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnIcC7gicqfu4A0sBIm89ghyk8Pk0FwAQ',
    appId: '1:191554436392:web:7ef681cb06c8fd2854641d',
    messagingSenderId: '191554436392',
    projectId: 'import-mark',
    authDomain: 'import-mark.firebaseapp.com',
    storageBucket: 'import-mark.appspot.com',
    measurementId: 'G-Y1NTGBBNRR',
  );
}
