import 'package:flutter/material.dart';
import 'package:get/get.dart';

class Languages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'Tired of the same? Upgrade your game! Download Shopaholic and join the fashion fame.':
              'Tired of the same? Upgrade your game! Download Shopaholic and join the fashion fame.',
          'Wished Items': 'Wished Items',
          'Spotted something you love? Wishlist it and let it know you\'re interested':
              'Spotted something you love? Wishlist it and let it know you\'re interested',
          'Flash Sales': 'Flash Sales',
          'Lightning Deals! Don\'t blink or these hot styles will vanish faster than your chance to say "Shopaholic!" ⚡️':
              'Lightning Deals! Don\'t blink or these hot styles will vanish faster than your chance to say "Shopaholic!" ⚡️',
          'Add to Cart': 'Add to Cart',
          'Found something oh-so-fine? Click "Add to Cart" and make it shine! ✨':
              'Found something oh-so-fine? Click "Add to Cart" and make it shine! ✨',
          'Exciting Deals': 'Exciting Deals',
          'Lightning speed, amazing savings! Shop Shopaholic\'s hot deals and checkout in a snap. Time to treat yourself!':
              'Lightning speed, amazing savings! Shop Shopaholic\'s hot deals and checkout in a snap. Time to treat yourself!',
          'Leave a Review': 'Leave a Review',
          'Did this item live up to the hype? Share your thoughts and unlock exclusive Shopaholic rewards!':
              'Did this item live up to the hype? Share your thoughts and unlock exclusive Shopaholic rewards!',
          'Home': 'Home',
          'Let\'s Get Started!': 'Let\'s Get Started!',
          'Let\'s Dive into Your Account': 'Let\'s Dive into Your Account',
          'Continue with Google': 'Continue with Google',
          'Continue with Apple': 'Continue with Apple',
          'Continue with Facebook': 'Continue with Facebook',
          'Continue with Twitter': 'Continue with Twitter',
          'Join Shopaholic': 'Join Shopaholic',
          'Embark on a Fashion Journey Tailored for You':
              'Embark on a Fashion Journey Tailored for You',
          'User Name': 'User Name',
          'I agree to Shopaholic': 'I agree to Shopaholic',
          ' Terms & Conditions.': ' Terms & Conditions.',
          'Welcome \nBack!': 'Welcome \nBack!',
          'UserName or Email': 'UserName or Email',
          'Remember Me': 'Remember Me',
          'We\'ve got you covered. Enter your registered email to reset your password. Will will send an OTP code to your email for the next steps.':
              'We\'ve got you covered. Enter your registered email to reset your password. Will will send an OTP code to your email for the next steps.',
          'Your Registered Email': 'Your Registered Email',
          'Send OTP Code': 'Send OTP Code',
          'Enter OTP Code': 'Enter OTP Code',
          'Please check your email inbox for a message from Shopaholic. Enter the one-time verification code bellow.':
              'Please check your email inbox for a message from Shopaholic. Enter the one-time verification code bellow.',
          'You can resend the code in ': 'You can resend the code in ',
          'seconds': 'seconds',
          'Resend Code': 'Resend Code',
          'Verify': 'Verify',
          'Secure Your Account': 'Secure Your Account',
          'Create a new password for Shopaholic account to keep it secure. Remember to choose a strong and unique password.':
              'Create a new password for Shopaholic account to keep it secure. Remember to choose a strong and unique password.',
          'Save': 'Save',
          'You\'re All Set': 'You\'re All Set',
          'Your Password Changed Successfully.':
              'Your Password Changed Successfully.',
          'Account': 'Account',
          'Orders': 'Orders',
          'Cart': 'Cart',
          'Wishlist': 'Wishlist',
          'Contact Us': 'Contact Us',
          'My Order': 'My Order',
          'Special Offers': 'Special Offers',
          'We make sure you get the offer': 'We make sure you get the offer',
          'New Arrivals': 'New Arrivals',
          'Flat and Heels': 'Flat and Heels',
          'Stand a chance to\nget rewarded': 'Stand a chance to\nget rewarded',
          'Trending Products': 'Trending Products',
          'Summer\'25 Collections': 'Summer\'25 Collections',
          'Beauty & Fashion': 'Beauty & Fashion',
          'Products': 'Products',
          'Sort': 'Sort',
          'Filter': 'Filter',
          'Apply': 'Apply',
          'Material': 'Material',
          'Variants': 'Variants',
          'Color': 'Color',
          'Product Details': 'Product Details',
          'No Wished Items!': 'No Wished Items!',
          'Checkout': 'Checkout',
          'Edit Product Variant': 'Edit Product Variant',
          'Promos & Vouchers': 'Promos & Vouchers',
          'Add to Wishlist': 'Add to Wishlist',
          'Wishlisted': 'Wishlisted',
          'Rating & Reviews': 'Rating & Reviews',
          'See less': 'See less',
          'Delivery Address': 'Delivery Address',
          'Your Order': 'Your Order',
          'Delivery': 'Delivery',
          'Payment Methods': 'Payment Methods',
          'Review Summary': 'Review Summary',
          'Confirm Order': 'Confirm Order',
          'Processing Payments...': 'Processing Payments...',
          'Order Confirmed': 'Order Confirmed',
          'View Orders': 'View Orders',
          'Active': 'Active',
          'Completed': 'Completed',
          'Canceled': 'Canceled',
          'Cancel Order': 'Cancel Order',
          'Track Order': 'Track Order',
          'Order has Arrived': 'Order has Arrived',
          'Delivery Status': 'Delivery Status',
          'Order Details': 'Order Details',
          'Rate your Order': 'Rate your Order',
          'Submit': 'Submit',
          'Promoted Products': 'Promoted Products',
          'Search History': 'Search History',
          'Recently Viewed': 'Recently Viewed',
          'Edit Profile': 'Edit Profile',
          'Account & Security': 'Account & Security',
          'Order History': 'Order History',
          'Notifications': 'Notifications',
          'Help & Supports': 'Help & Supports',
          'Are you sure want to log out?': 'Are you sure want to log out?',
          'You may also like': 'You may also like',
          'No Product Carted!': 'No Product Carted!',
          'Are you sure you want to cancel the order?':
              'Are you sure you want to cancel the order?',
          'It\'s okay to change your mind! your payment will be safely refunded.':
              'It\'s okay to change your mind! your payment will be safely refunded.',
          ' Terms & Conditions': ' Terms & Conditions',
          'may apply.': 'may apply.',
          'No, Don\'t Cancel': 'No, Don\'t Cancel',
          'Yes, Cancel Order': 'Yes, Cancel Order',
          'Order Canceled Successfully!': 'Order Canceled Successfully!',
          'Buy': 'Buy',
          'Ends in': 'Ends in',
          'Profile': 'Profile',
          'Skip': 'Skip',
          'Done': 'Done',
          'Login': 'Login',
          'Email': 'Email',
          'Password': 'Password',
          'Confirm Password': 'Confirm Password',
          'Continue': 'Continue',
          'Create new password': 'Create new password',
          'Confirm new password': 'Confirm new password',
          'Forgot Password?': 'Forgot Password?',
          'Don\'t have an account?': 'Don\'t have an account?',
          'Register': 'Register',
          'Or': 'Or',
          'Already have an account?': 'Already have an account?',
          'Language': 'Language',
          'View All': 'View All',
          'See more': 'See more',
          'Search': 'Search',
          'Settings': 'Settings',
          'Help Center': 'Help Center',
          'About Us': 'About Us',
          'LogOut': 'LogOut',
          'Log Out Account': 'Log Out Account',
          'Are you sure, you want to log out?':
              'Are you sure, you want to log out?',
          'About': 'About',
          'Categories': 'Categories',
          'Cancel': 'Cancel',
          'Ok': 'Ok',
          'Have a Promo Code?': 'Have a Promo Code?',
          'Enter Code Here': 'Enter Code Here',
          'Redeem': 'Redeem',
          'Full Name': 'Full Name',
          'Phone Number': 'Phone Number',
          'Gender': 'Gender',
          'Date of Birth': 'Date of Birth',
          'Theme': 'Theme',
          'Awesome! Product Carted': 'Awesome! Product Carted',
          'Want to Continue Shopping': 'Want to Continue Shopping',
          'Continue Shopping': 'Continue Shopping',
          'Go to Cart': 'Go to Cart',
          'Chat with Seller': 'Chat with Seller',
          'Chat with CustomerCare': 'Chat with CustomerCare',
          'Username or Email': 'Username or Email',
          'Name': 'Name',
          'Privacy Policy': 'Privacy Policy',
          'Return Order': 'Return Order',
          'Return Reason': 'Return Reason',
          'Cancellation Reason': 'Cancellation Reason',
          'Confirm': 'Confirm',
          'Order is being Processed to be Returned': 'Order is being Processed to be Returned',
          'Go to Home': 'Go to Home',
          'Check Out Our New Deals!': 'Check Out Our New Deals!',
          'Want to Use this Promo?': 'Want to Use this Promo?',
          'Are you sure want to use this promo?': 'Are you sure want to use this promo?',
          'No': 'No',
          'Yes': 'Yes',
          'Promos didn\'t Redeemed': 'Promos didn\'t Redeemed',
          'Promos Redeemed Successfully': 'Promos Redeemed Successfully',
          'Ask Questions': 'Ask Questions',
          'Select gender': 'Select gender',
          'Male': 'Male',
          'Female': 'Female',
          'Others': 'Others',
          'Enter Number': 'Enter Number',
          'Sold': 'Sold',
          'Type': 'Type',
          'Reset': 'Reset',
          'Sorry': 'Sorry',
          "You don't have any notification yet.": "You don't have any notification yet.",
          'Back': 'Back',
          'No Reviews Found': 'No Reviews Found',
          'No Q&A Found': 'No Q&A Found',
          "Select Address": 'Select Address',
          "No Address Selected": 'No Address Selected',
          'Select Promo': 'Select Promo',
          'Subtotal': 'Subtotal',
          'Total': 'Total',
          'Address Label': 'Address Label',
          'Phone No.': 'Phone No.',
          'City': 'City',
          'District': 'District',
          'Select Area': 'Select Area',
          'Address': 'Address',
          'Inside Dhaka': 'Inside Dhaka',
          'Outside Dhaka': 'Outside Dhaka',
          'Add Address Details': 'Add Address Details',
          'Payment Gateway': 'Payment Gateway',
          'Paid': 'Paid',
          'Due': 'Due',
          'Pending': 'Pending',
          'Confirmed': 'Confirmed',
          'Shipped': 'Shipped',
          'Delivered': 'Delivered',
          'Cancelled': 'Cancelled',
          'Returned': 'Returned',
          'Rejected': 'Rejected',
          'Shipping Charge': 'Shipping Charge',
          'Discount': 'Discount',
          'Tax': 'Tax',
          'Vat': 'Vat',
          'Information Details': 'Information Details',
          'Purchase Date': 'Purchase Date',
          'Purchase Time': 'Purchase Time',
          'Invoice Number': 'Invoice Number',
          "Generate Invoice": 'Generate Invoice',
          'Order has been': 'Order has been',
          'Status': 'Status',
          'Order ID': 'Order ID',
          'No Order Placed!': 'No Order Placed!',
          'Submit Review': 'Submit Review',
          'Size': 'Size',
          'Quantity': 'Quantity',
          'Price': 'Price',
          'Make Payment': 'Make Payment',
          'No Promos Selected': 'No Promos Selected',
          'Pay' : 'Pay',
          'InvoiceID': 'Invoice ID',
          'Phone': 'Phone',
          'User Information': 'User Information',
          'You are Unauthenticated.': 'You are Unauthenticated.',
          'Please Log In.': 'Please Log In.',
          'File': 'File',
          'Camera': 'Camera',
          'FAQ': 'FAQ',
          'Terms of Service': 'Terms of Service',
          'About us': 'About us',
          'Rate us': 'Rate us',
          'Visit Our Website': 'Visit Our Website',
          'Accessibility': 'Accessibility',
          'FeedBack': 'FeedBack',
          'Contact Support': 'Contact Support',
          'Change Password': 'Change Password',
          'We are sorry!': 'We are sorry!',
          'Something went wrong. Please try again.': 'Something went wrong. Please try again.',
          'Item': 'Item',
          'Items': 'Items',

        },
        'bn_BD': {
          'Awesome! Product Carted':'অসাধারণ! প্রোডাক্ট কার্টেড',
          'Want to Continue Shopping':'শপিং চালিয়ে যেতে চাই',
          'Continue Shopping':'শপিং চালিয়ে যান',
          'Go to Cart':'কার্টে যান',
          'Chat with Seller':'সেলার সাথে চ্যাট করুন',
          'Chat with CustomerCare':'কাস্টমার কেয়ারের সাথে চ্যাট করুন',
          'Username or Email':'নাম বা ইমেল',
          'Name':'নাম',
          'Privacy Policy':'গোপনীয়তা নীতি',
          'Return Order':'রিটার্ন অর্ডার',
          'Return Reason':'রিটার্নের কারণ',
          'Cancellation Reason':'বাতিলের কারণ',
          'Confirm':'কনফার্ম',
          'Order is being Processed to be Returned':'প্রোডাক্ট ফেরত দেওয়ার প্রক্রিয়া চলছে',
          'Go to Home':'হোম এ যান',
          'Check Out Our New Deals!':'আমাদের নতুন ডিল দেখুন!',
          'Want to Use this Promo?':'এই প্রোমো ব্যবহার করতে চান?',
          'Are you sure want to use this promo?':'আপনি কি নিশ্চিত এই প্রচারটি ব্যবহার করতে চান?',
          'No':'না',
          'Yes':'হ্যাঁ',
          'Promos didn\'t Redeemed':'প্রোমো রিডিম করা হয়নি',
          'Promos Redeemed Successfully':'প্রোমো সফলভাবে রিডিম হয়েছে',
          'Ask Questions':'প্রশ্ন জিজ্ঞাসা করুন',
          'Select gender':'লিঙ্গ নির্বাচন করুন',
          'Male':'পুরুষ',
          'Female':'মহিলা',
          'Others':'অন্যান্য',
          'Enter Number':'নম্বর লিখুন',
          'Tired of the same? Upgrade your game! Download Shopaholic and join the fashion fame.':
              'একই জিনিসে ক্লান্ত! নিজেকে পরিবর্তন করুন খুব সহজে, Shopaholic ডাউনলোড করুন এবং ফ্যাশন ফেমে যোগ দিন।',
          'Wished Items': 'উইশলিস্ট আইটেম',
          'Spotted something you love? Wishlist it and let it know you\'re interested':
              'আপনার পছন্দের কিছু খুঁজে পেয়েছেন? এটিকে উইশলিস্ট করুন যেন পরবর্তীতে খুঁজে পেতে সুবিধা হয় ',
          'Flash Sales': 'ফ্ল্যাশ সেলস',
          'Lightning Deals! Don\'t blink or these hot styles will vanish faster than your chance to say "Shopaholic!" ⚡️':
              'ফ্ল্যাশ ডিলস! পলক ফেলবেন না কারণ এই হট স্টাইলগুলি আপনার "Shopaholic" বলার আগেই দ্রুত অদৃশ্য হয়ে যাবে। ⚡️',
          'Add to Cart': 'কার্টে যোগ করুন',
          'Found something oh-so-fine? Click "Add to Cart" and make it shine! ✨':
              'আকর্ষণীয় কিছু পাওয়া গেছে? "কার্টে যোগ করুন" এ ক্লিক করুন এবং এটিকে নিজের  করুন! ✨',
          'Exciting Deals': 'রোমাঞ্চকর ডিলস',
          'Lightning speed, amazing savings! Shop Shopaholic\'s hot deals and checkout in a snap. Time to treat yourself!':
              'আশ্চর্যজনক সেভিংস! Shopaholic এ হট ডিল কিনুন এবং সহজে চেকআউট করুন। নিজেকে ট্রিট দেওয়ার সময়!',
          'Leave a Review': 'রিভিউ দিন',
          'Did this item live up to the hype? Share your thoughts and unlock exclusive Shopaholic rewards!':
              'এই আইটেম টি ভালো হয়েছে ? আপনার রিভিউ শেয়ার করুন এবং Shopaholic পুরস্কার আনলক করুন!',
          'Home': 'হোম',
          'Profile': 'প্রোফাইল',
          'Skip': 'এড়িয়ে যান',
          'Done': 'সম্পন্ন',
          'Login': 'লগইন',
          'Email': 'ইমেইল',
          'Password': 'পাসওয়ার্ড',
          'Confirm Password': 'পাসওয়ার্ড নিশ্চিত করুন',
          'Continue': 'চালিয়ে যান',
          'Create new password': 'নতুন পাসওয়ার্ড তৈরি করুন',
          'Confirm new password': 'নতুন পাসওয়ার্ড নিশ্চিত করুন',
          'Forgot Password?': 'পাসওয়ার্ড ভুলে গেছেন?',
          'Don\'t have an account?': 'অ্যাকাউন্ট নেই?',
          'Register': 'রেজিস্টার',
          'Or': 'অথবা',
          'Already have an account?': 'ইতিমধ্যে একটি অ্যাকাউন্ট আছে?',
          'Language': 'ভাষা',
          'View All': 'সব দেখ',
          'See more': 'আরো দেখুন',
          'Search': 'অনুসন্ধান করুন',
          'Settings': 'সেটিংস ',
          'About Us': 'আমাদের সম্পর্কে',
          'LogOut': 'লগ আউট',
          'Log Out Account': 'অ্যাকাউন্ট লগ আউট?',
          'Are you sure, you want to log out?':
              'আপনি কি নিশ্চিত লগ আউট করতে চান?',
          'About': 'সম্পর্কিত',
          'Categories': 'ক্যাটেগোরিস',
          'Cancel': 'বাতিল',
          'Ok': 'ওকে',
          'Let\'s Get Started!': 'আসুন শুরু করি!',
          'Let\'s Dive into Your Account': 'আসুন আপনার অ্যাকাউন্টে ঢুকে পড়ি',
          'Continue with Google': 'Google এর মাধ্যমে লগইন করুন',
          'Continue with Apple': 'Apple এর মাধ্যমে লগইন করুন',
          'Continue with Facebook': ' Facebook এর মাধ্যমে লগইন করুন',
          'Continue with Twitter': 'Twitter এর মাধ্যমে লগইন করুন',
          'Join Shopaholic': 'Shopaholic জয়েন করুন',
          'Embark on a Fashion Journey Tailored for You':
              'আপনার জন্য তৈরি একটি ফ্যাশন জার্নি শুরু করুন',
          'User Name': 'ইউজার নাম',
          'I agree to Shopaholic': 'আমি Shopaholic শর্তাবলীতে ',
          ' Terms & Conditions.': ' সম্মত',
          'Welcome \nBack!': 'ওয়েলকাম ব্যাক!',
          'UserName or Email': 'ইউজার নাম/ইমেল',
          'Remember Me': 'আমাকে মনে রেখো',
          'We\'ve got you covered. Enter your registered email to reset your password. Will will send an OTP code to your email for the next steps.':
              'আপনার পাসওয়ার্ড রিসেট করতে আপনার নিবন্ধিত ইমেল লিখুন. পরবর্তী পদক্ষেপের জন্য আপনার ইমেলে একটি OTP কোড পাঠানো হবে ।',
          'Your Registered Email': 'আপনার নিবন্ধিত ইমেল',
          'Send OTP Code': 'ওটিপি কোড পাঠান',
          'Enter OTP Code': 'ওটিপি কোড লিখুন',
          'Please check your email inbox for a message from Shopaholic. Enter the one-time verification code bellow.':
              'Shopaholic থেকে একটি মেসেজ জন্য আপনার ইমেল ইনবক্স চেক করুন. নিচের ওটিপি কোডটি লিখুন।',
          'You can resend the code in ': 'ওটিপি কোডটি পুনরায় পাঠাতে পারেন',
          'seconds': 'সেকেন্ড',
          'Resend Code': 'পুনরায় কোড পাঠান',
          'Verify': 'যাচাই করুন',
          'Secure Your Account': 'আপনার অ্যাকাউন্ট সুরক্ষিত করুন',
          'Create a new password for Shopaholic account to keep it secure. Remember to choose a strong and unique password.':
              'Shopaholic অ্যাকাউন্ট সুরক্ষিত রাখতে একটি নতুন পাসওয়ার্ড তৈরি করুন। একটি শক্তিশালী এবং অনন্য পাসওয়ার্ড দিতে ভুলবেন না।',
          'Save': 'সেভ',
          'You\'re All Set': 'আপনি সম্পূর্ণ প্রস্তুত',
          'Your Password Changed Successfully.':
              'আপনার পাসওয়ার্ড সফলভাবে পরিবর্তন হয়েছে।',
          'Account': 'অ্যাকাউন্ট',
          'Orders': 'অর্ডারস',
          'Cart': 'কার্ট',
          'Wishlist': 'উইশলিস্ট',
          'Contact Us': 'যোগাযোগ করুন',
          'My Order': 'আমার অর্ডারস',
          'Special Offers': 'ধামাকা অফার',
          'We make sure you get the offer':
              'আমরা নিশ্চিত করি আপনি অফার পেয়েছেন',
          'New Arrivals': 'নতুন আগমন',
          'Flat and Heels': 'ফ্ল্যাট এবং হিল',
          'Stand a chance to\nget rewarded': 'পুরস্কার পাওয়ার সুযোগ পান',
          'Trending Products': 'ট্রেন্ডিং প্রোডাক্ট',
          'Summer\'25 Collections': 'সামার\'25 কালেকশন',
          'Beauty & Fashion': 'সৌন্দর্য ও ফ্যাশন',
          'Products': 'প্রোডাক্ট',
          'Sort': 'সাজানো',
          'Filter': 'ফিল্টার',
          'Apply': 'আবেদন',
          'Material': 'উপাদান',
          'Variants': 'ভেরিয়েন্ট',
          'Color': 'রঙ',
          'Product Details': 'প্রোডাক্টের বিবরণ',
          'No Wished Items!': 'উইশড আইটেম নেই!',
          'Checkout': 'চেকআউট',
          'Edit Product Variant': 'চেঞ্জ প্রোডাক্ট ভেরিয়েন্ট',
          'Promos & Vouchers': 'প্রোমো ও ভাউচার',
          'Add to Wishlist': 'উইশলিস্ট যোগ করুন',
          'Wishlisted': 'উইশলিস্টেড ',
          'Rating & Reviews': 'রেটিং ও রিভিউ',
          'See less': 'কম দেখুন',
          'Delivery Address': 'ডেলিভারির ঠিকানা',
          'Your Order': 'আপনার অর্ডার',
          'Delivery': 'ডেলিভারি',
          'Payment Methods': 'পেমেন্ট পদ্ধতি',
          'Review Summary': 'পর্যালোচনার সারাংশ',
          'Confirm Order': 'অর্ডার কনফার্ম',
          'Processing Payments...': 'প্রসেসিং পেমেন্ট...',
          'Order Confirmed': 'অর্ডার কনফার্ম',
          'View Orders': 'অর্ডার দেখুন',
          'Active': 'সচল',
          'Completed': 'সম্পূর্ণ',
          'Canceled': 'বাতিল',
          'Cancel Order': 'অর্ডার বাতিল',
          'Track Order': 'ট্র্যাক অর্ডার',
          'Order has Arrived': 'অর্ডার এসেছে',
          'Delivery Status': 'ডেলিভারি স্ট্যাটাস',
          'Order Details': 'অর্ডারের বিস্তারিত',
          'Rate your Order': 'আপনার অর্ডার রেটিং করুন',
          'Submit': 'জমা দিন',
          'Promoted Products': 'প্রচারিত পণ্য',
          'Search History': 'অনুসন্ধানের ইতিহাস',
          'Recently Viewed': 'সম্প্রতি দেখা হয়েছে',
          'Edit Profile': 'প্রোফাইল এডিট',
          'Account & Security': 'অ্যাকাউন্ট এবং নিরাপত্তা',
          'Order History': 'অর্ডার ইতিহাস',
          'Notifications': 'নোটিফিকেশন্স',
          'Help & Supports': 'সাহায্য এবং সমর্থন',
          'You may also like': 'আপনি পছন্দ করতে পারেন',
          'No Product Carted!': 'কোন প্রোডাক্ট কার্টেড নেই!',
          'Are you sure you want to cancel the order?':
              'আপনি কি নিশ্চিত যে আপনি অর্ডারটি বাতিল করতে চান?',
          'It\'s okay to change your mind! your payment will be safely refunded.':
              'আপনার মন পরিবর্তন করা ঠিক আছে! আপনার পেমেন্ট নিরাপদে ফেরত দেওয়া হবে।',
          ' Terms & Conditions': ' শর্তাবলী',
          'may apply.': ' প্রযোজ্য হতে পারে',
          'No, Don\'t Cancel': 'না, বাতিল করবেন না',
          'Yes, Cancel Order': 'হ্যাঁ, অর্ডার বাতিল করুন',
          'Order Canceled Successfully!': 'অর্ডার সফলভাবে বাতিল হয়েছে',
          'Buy': 'কিনুন',
          'Ends in': 'শেষ হবে',
          'Have a Promo Code?': 'প্রোমো কোড আছে?',
          'Enter Code Here': 'এখানে কোড লিখুন',
          'Redeem': 'রিডিম করুন',
          'Full Name': 'নাম',
          'Phone Number': 'ফোন',
          'Gender': 'লিঙ্গ',
          'Date of Birth': 'জন্ম তারিখ',
          'Theme': 'থিম',
          'Sold': 'বিক্রি হয়েছে',
          'Type': 'ধরন',
          'Reset': 'রিসেট',
          'Sorry': 'দুঃখিত',
          "You don't have any notification yet.": "আপনার কাছে এখনও কোনো নোটিফিকেশন নেই।",
          'Back': 'পিছনে',
          'No Reviews Found': 'কোনো রিভিউ পাওয়া যায়নি',
          'No Q&A Found': 'কোনো প্রশ্নোত্তর পাওয়া যায়নি',
          "Select Address": 'ঠিকানা নির্বাচন করুন',
          "No Address Selected": 'কোনো ঠিকানা নির্বাচন করা হয়নি',
          'Select Promo': 'প্রমো নির্বাচন করুন',
          'Subtotal': 'সাবটোটাল',
          'Total': 'মোট',
          'Address Label': 'ঠিকানার লেবেল',
          'Phone No.': 'ফোন নম্বর',
          'City': 'শহর',
          'District': 'জেলা',
          'Select Area': 'এলাকা নির্বাচন করুন',
          'Address': 'ঠিকানা',
          'Inside Dhaka': 'ঢাকার ভিতরে',
          'Outside Dhaka': 'ঢাকার বাইরে',
          'Add Address Details': 'ঠিকানার বিবরণ যোগ করুন',
          'Payment Gateway': 'পেমেন্ট গেটওয়ে',
          'Paid': 'পরিশোধ',
          'Due': 'বকেয়া',
          'Pending': 'অপেক্ষমাণ',
          'Confirmed': 'নিশ্চিত',
          'Shipped': 'পাঠানো হয়েছে',
          'Delivered': 'বিতরণ করা হয়েছে',
          'Cancelled': 'বাতিল করা হয়েছে',
          'Returned': 'ফেরত দেওয়া হয়েছে',
          'Rejected': 'প্রত্যাখ্যাত',
          'Shipping Charge': 'শিপিং চার্জ',
          'Discount': 'ছাড়',
          'Tax': 'কর',
          'Vat': 'ভ্যাট',
          'Information Details': 'তথ্যের বিবরণ',
          'Purchase Date': 'ক্রয়ের তারিখ',
          'Purchase Time': 'ক্রয়ের সময়',
          'Invoice Number': 'চালান নম্বর',
          "Generate Invoice": 'চালান তৈরি করুন',
          'Order has been': 'অর্ডার করা হয়েছে',
          'Status': 'অবস্থা',
          'Order ID': 'অর্ডার আইডি',
          'No Order Placed!': 'কোনো অর্ডার দেওয়া হয়নি!',
          'Submit Review' : 'সাবমিট রিভিউ',
          'Size': 'সাইজ',
          'Quantity': 'পরিমাণ',
          'Price': 'মূল্য',
          'Make Payment': 'পেমেন্ট করুন',
          'No Promos Selected': 'কোন প্রোমো নির্বাচন করা হয়নি',
          'Pay' : 'পরিশোধ',
          'InvoiceID': 'চালান নম্বর',
          'Phone': 'ফোন',
          'User Information': 'গ্রাহকের তথ্য',
          'You are Unauthenticated.': 'আপনার পরিচয় যাচাই হয়নি।',
          'Please Log In.': 'দয়া করে লগ ইন করুন।',
          'File': 'ফাইল',
          'Camera': 'ক্যামেরা',
          'FAQ': 'এফএকিউ',
          'Terms of Service': 'পরিষেবার শর্তাবলী',
          'About us': 'আমাদের সম্পর্কে',
          'Rate us': 'আমাদের রেট করুন',
          'Visit Our Website': 'আমাদের ওয়েবসাইট দেখুন',
          'Accessibility': 'প্রবেশযোগ্যতা',
          'FeedBack': 'মতামত',
          'Contact Support': 'সাহায্যের জন্য যোগাযোগ করুন',
          'Change Password': 'পাসওয়ার্ড পরিবর্তন করুন',
          'We are sorry!': 'আমরা দুঃখিত!',
          'Something went wrong. Please try again.': 'কিছু ভুল হয়েছে। অনুগ্রহ করে আবার চেষ্টা করুন।',
          'Item': 'আইটেম',
          'Items': 'আইটেমগুলি',

        },
        'hi_IN': {
          //hindi
          'Awesome! Product Carted':'बहुत बढ़िया! उत्पाद कार्टेड',
          'Want to Continue Shopping':'खरीदारी जारी रखना चाहते हैं',
          'Continue Shopping':'खरीदारी जारी रखें',
          'Go to Cart':'गाड़ी पर जाना',
          'Chat with Seller':'विक्रेता के साथ चैट करें',
          'Chat with CustomerCare':'कस्टमर केयर के साथ चैट करें',
          'Username or Email':'उपयोगकर्ता का नाम या ईमेल',
          'Name':'नाम',
          'Privacy Policy':'गोपनीयता नीति',
          'Return Order':'वापसी आदेश',
          'Return Reason':'रिटर्न वजह',
          'Cancellation Reason':'रद्द करने का कारण',
          'Confirm':'पुष्टि करना',
          'Order is being Processed to be Returned':'ऑर्डर लौटाने की प्रक्रिया चल रही है',
          'Go to Home':'घर जाओ',
          'Check Out Our New Deals!':'हमारे नए सौदे देखें!',
          'Want to Use this Promo?':'क्या आप इस प्रोमो का उपयोग करना चाहते हैं?',
          'Are you sure want to use this promo?':'क्या आप वाकई इस प्रोमो का उपयोग करना चाहते हैं?',
          'No':'नहीं',
          'Yes':'हाँ',
          'Promos didn\'t Redeemed':'प्रोमो रिडीम नहीं किए गए',
          'Promos Redeemed Successfully':'प्रोमो सफलतापूर्वक भुनाया गया',
          'Ask Questions':'प्रश्न पूछें',
          'Select gender':'लिंग चुनें',
          'Male':'पुरुष',
          'Female':'महिला',
          'Others':'अन्य',
          'Enter Number':'नंबर डालें',
          'Tired of the same? Upgrade your game! Download Shopaholic and join the fashion fame.':
              'उसी से थक गए? अपना गेम अपग्रेड करें! शॉपहॉलिक डाउनलोड करें और फैशन प्रसिद्धि में शामिल हों।',
          'Wished Items': 'इच्छित वस्तुएँ',
          'Spotted something you love? Wishlist it and let it know you\'re interested':
              'कुछ ऐसा देखा जो आपको पसंद हो? इसे इच्छा सूची में डालें और बताएं कि आप रुचि रखते हैं',
          'Flash Sales': 'फ़्लैश बिक्री',
          'Lightning Deals! Don\'t blink or these hot styles will vanish faster than your chance to say "Shopaholic!" ⚡️':
              'बिजली के सौदे! पलकें न झपकाएं वरना ये हॉट स्टाइल आपके "शॉपहॉलिक!" कहने के मौके से भी ज्यादा तेजी से गायब हो जाएंगे। ⚡️',
          'Add to Cart': 'कार्ट में जोड़ें',
          'Found something oh-so-fine? Click "Add to Cart" and make it shine! ✨':
              'कुछ मिला ओह-बहुत बढ़िया? "कार्ट में जोड़ें" पर क्लिक करें और इसे चमकाएं! ✨',
          'Exciting Deals': 'रोमांचक सौदे',
          'Lightning speed, amazing savings! Shop Shopaholic\'s hot deals and checkout in a snap. Time to treat yourself!':
              'बिजली की गति, अद्भुत बचत! शॉपहॉलिक के हॉट डील्स खरीदें और तुरंत चेकआउट करें। खुद का इलाज करने का समय!',
          'Leave a Review': 'समीक्षा लिखें',
          'Did this item live up to the hype? Share your thoughts and unlock exclusive Shopaholic rewards!':
              'क्या यह आइटम प्रचार के अनुरूप रहा? अपने विचार साझा करें और विशेष शॉपहॉलिक पुरस्कार अनलॉक करें!',
          'Hi': 'नमस्ते',
          'Home': 'घर',
          'Profile': 'प्रोफ़ाइल',
          'Skip': 'छोडना',
          'Done': 'हो गया',
          'Login': 'लॉग इन करें',
          'Email': 'ईमेल',
          'Password': 'पासवर्ड',
          'Confirm Password': 'पासवर्ड की पुष्टि कीजिये',
          'Continue': 'जारी रखना',
          'Create new Password?': 'नया पासवर्ड बनाएं',
          'Create new password': 'नया पासवर्ड बनाएं',
          'Confirm new password': 'नए पासवर्ड की पुष्टि करें',
          'Forgot Password?': 'पासवर्ड भूल गए?',
          'Don\'t have an account?': 'कोई खाता नहीं है?',
          'Register': 'पंजीकरण करवाना',
          'Or': 'या',
          'Sign Up': 'साइन अप करें',
          'Already have an account?': 'क्या आपके पास पहले से एक खाता मौजूद है?',
          'Language': 'भाषा',
          'View All': 'सभी को देखें',
          'See more': 'और देखें',
          'Search': 'खोज',
          'Warning!': 'चेतावनी',
          'Recent Result': 'हालिया परिणाम',
          'Settings': 'समायोजन',
          'About Us': 'हमारे बारे में',
          'LogOut': 'लॉग आउट',
          'Log Out Account': 'लॉग आउट खाता',
          'Are you sure, you want to log out?':
              'क्या आप वाकई लॉग आउट करना चाहते हैं?',
          'Categories': 'श्रेणियाँ',
          'Cancel': 'रद्द करना',
          'Ok': 'ठीक है',
          'Can\'t Skip!': 'छोड़ नहीं सकते!',
          'Let\'s Get Started!': 'आएँ शुरू करें',
          'Let\'s Dive into Your Account': 'आइए आपके खाते में गोता लगाएँ',
          'Continue with Google': 'Google के साथ जारी रखें',
          'Continue with Apple': 'Apple के साथ जारी रखें',
          'Continue with Facebook': 'Facebook के साथ जारी रखें',
          'Continue with Twitter': 'Twitter के साथ जारी रखें',
          'Join Shopaholic': 'Shopaholic से जुड़ें',
          'Embark on a Fashion Journey Tailored for You':
              'आपके लिए तैयार फैशन यात्रा पर निकलें',
          'User Name': 'उपयोगकर्ता नाम',
          'I agree to Shopaholic': 'मैं Shopaholic नियम और शर्तों से सहमत हूं।',
          ' Terms & Conditions.': ' Terms & Conditions.',
          'Welcome \nBack!': 'वापस स्वागत है!',
          'UserName or Email': 'उपयोगकर्ता का नाम या ईमेल',
          'Remember Me': 'मुझे याद करो',
          'We\'ve got you covered. Enter your registered email to reset your password. Will will send an OTP code to your email for the next steps.':
              'हमने आपका ध्यान रखा है। अपना पासवर्ड रीसेट करने के लिए अपना पंजीकृत ईमेल दर्ज करें। अगले चरण के लिए विल आपके ईमेल पर एक ओटीपी कोड भेजेगा।',
          'Your Registered Email': 'आपका पंजीकृत ईमेल',
          'Send OTP Code': 'ओटीपी कोड भेजें',
          'Enter OTP Code': 'ओटीपी कोड दर्ज करें',
          'Please check your email inbox for a message from Shopaholic. Enter the one-time verification code bellow.':
              'कृपया शॉपहोलिक के संदेश के लिए अपना ईमेल इनबॉक्स जांचें। नीचे एक बार का सत्यापन कोड दर्ज करें।',
          'You can resend the code in ': 'आप कोड को दोबारा भेज सकते हैं',
          'seconds': 'सेकंड',
          'Resend Code': 'पुन: कोड भेजे',
          'Verify': 'सत्यापित करें',
          'Secure Your Account': 'अपने खाते को सुरक्षित करें',
          'Create a new password for Shopaholic account to keep it secure. Remember to choose a strong and unique password.':
              'Shopaholic खाते को सुरक्षित रखने के लिए एक नया पासवर्ड बनाएं। एक मजबूत और अद्वितीय पासवर्ड चुनना याद रखें।',
          'Save': 'बचाना',
          'You\'re All Set': 'तुम सब सेट हो',
          'Your Password Changed Successfully.':
              'आपका पासवर्ड सफलतापूर्वक बदल गया।',
          'Account': 'खाता',
          'Orders': 'ऑर्डर्स',
          'Cart': 'कार्ट',
          'Wishlist': 'इच्छा सूची',
          'Contact Us': 'संपर्क करें',
          'My Order': 'मेरा ऑर्डर',
          'Special Offers': 'खास पेशकश',
          'We make sure you get the offer':
              'हम सुनिश्चित करते हैं कि आपको प्रस्ताव मिले',
          'New Arrivals': 'नवागन्तुक',
          'Flat and Heels': 'फ्लैट और हील्स',
          'Stand a chance to\nget rewarded': 'पुरस्कार पाने का मौका पाएं',
          'Trending Products': 'ट्रेंडिंग उत्पाद',
          'Summer\'25 Collections': 'ग्रीष्मकालीन\'25 संग्रह',
          'Beauty & Fashion': 'सौंदर्य और फैशन',
          'Products': 'उत्पाद',
          'Sort': 'सॉर्ट करें',
          'Filter': 'फ़िल्टर',
          'Apply': 'लागू करना',
          'Material': 'सामग्री',
          'Variants': 'वेरिएंट',
          'Color': 'रंग',
          'Product Details': 'उत्पाद विवरण',
          'No Wished Items!': 'कोई वांछित वस्तु नहीं!',
          'Checkout': 'चेक आउट',
          'Edit Product Variant': 'उत्पाद संस्करण संपादित करें',
          'Promos & Vouchers': 'प्रोमो और वाउचर',
          'Add to Wishlist': 'इच्छा सूची में जोड़ें',
          'Wishlisted': 'इच्छासूचीबद्ध',
          'Rating & Reviews': 'रेटिंग एवं समीक्षाएं',
          'See less': 'कम देखें',
          'Delivery Address': 'डिलिवरी का पता',
          'Your Order': 'आपका ऑर्डर',
          'Delivery': 'डिलीवरी',
          'Payment Methods': 'भुगतान की विधि',
          'Review Summary': 'समीक्षा सारांश',
          'Confirm Order': 'आदेश की पुष्टि',
          'Processing Payments...': 'भुगतान संसाधित हो रहा है...',
          'Order Confirmed': 'ऑर्डर की पुष्टि की गई',
          'View Orders': 'आदेश देखें',
          'Active': 'सक्रिय',
          'Completed': 'पुरा होना',
          'Canceled': 'रद्द',
          'Cancel Order': 'ऑर्डर रद्द करें',
          'Track Order': 'ऑर्डर पर नज़र रखना',
          'Order has Arrived': 'ऑर्डर आ गया है',
          'Delivery Status': 'डिलीवरी स्टेटस',
          'Order Details': 'ऑर्डर का विवरण',
          'Rate your Order': 'अपने ऑर्डर को रेटिंग दें',
          'Submit': 'जमा करना',
          'Promoted Products': 'प्रचारित उत्पाद',
          'Search History': 'खोज इतिहास',
          'Recently Viewed': 'हाल में देखा गया',
          'Edit Profile': 'प्रोफ़ाइल संपादित करें',
          'Account & Security': 'खाते की सुरक्षा',
          'Order History': 'आदेश इतिहास',
          'Notifications': 'सूचनाएं',
          'Help & Supports': 'सहायता एवं समर्थन',
          'You may also like': 'आपको यह भी पसंद आ सकता हैं',
          'No Product Carted!': 'कोई उत्पाद कार्टेड नहीं!',
          'Are you sure you want to cancel the order?':
              'क्या आप वाकई ऑर्डर रद्द करना चाहते हैं?',
          'It\'s okay to change your mind! your payment will be safely refunded.':
              'अपना मन बदलना ठीक है! आपका भुगतान सुरक्षित रूप से वापस कर दिया जाएगा।',
          ' Terms & Conditions': ' नियम एवं शर्तें',
          ' may apply.': 'लागू हो सकते हैं।',
          'No, Don\'t Cancel': 'नहीं, रद्द मत करो',
          'Yes, Cancel Order': 'हां, ऑर्डर रद्द करें',
          'Order Canceled Successfully!': 'आदेश सफलतापूर्वक रद्द किया गया',
          'Buy': 'खरीदें',
          'Ends in': 'में समाप्त',
          'Have a Promo Code?': 'क्या प्रोमो कोड है?',
          'Enter Code Here': 'यहाँ कोड दर्ज करें',
          'Redeem': 'एवज',
          'Full Name': 'पूरा नाम',
          'Phone Number': 'फ़ोन नंबर',
          'Gender': 'लिंग',
          'Date of Birth': 'जन्म की तारीख',
          'Theme': 'विषय',
          'Sold': 'बिक चुका है',
          'Type': 'प्रकार',
          'Reset': 'रीसेट',
          'Sorry': 'माफ़ कीजिये',
          "You don't have any notification yet.": "आपके पास अभी तक कोई सूचना नहीं है।",
          'Back': 'वापस',
          'No Reviews Found': 'कोई समीक्षा नहीं मिली',
          'No Q&A Found': 'कोई प्रश्नोत्तर नहीं मिला',
          "Select Address": 'पता चुनें',
          "No Address Selected": 'कोई पता नहीं चुना गया',
          'Select Promo': 'प्रोमो चुनें',
          'Subtotal': 'उप-योग',
          'Total': 'कुल',
          'Address Label': 'पता लेबल',
          'Phone No.': 'फ़ोन नंबर',
          'City': 'शहर',
          'District': 'जिला',
          'Select Area': 'क्षेत्र चुनें',
          'Address': 'पता',
          'Inside Dhaka': 'ढाका के अंदर',
          'Outside Dhaka': 'ढाका के बाहर',
          'Add Address Details': 'पता विवरण जोड़ें',
          'Payment Gateway': 'भुगतान गेटवे',
          'Paid': 'भुगतान किया गया',
          'Due': 'देय',
          'Pending': 'लंबित',
          'Confirmed': 'पुष्टि की गई',
          'Shipped': 'चालू',
          'Delivered': 'डिलीवर किया गया',
          'Cancelled': 'रद्द कर दिया गया',
          'Returned': 'वापस किया गया',
          'Rejected': 'अस्वीकृत',
          'Shipping Charge': 'शिपिंग शुल्क',
          'Discount': 'छूट',
          'Tax': 'कर',
          'Vat': 'वैट',
          'Information Details': 'जानकारी विवरण',
          'Purchase Date': 'खरीद की तारीख',
          'Purchase Time': 'खरीद का समय',
          'Invoice Number': 'चालान नंबर',
          "Generate Invoice": 'चालान बनाएं',
          'Order has been': 'आदेश किया गया है',
          'Status': 'स्थिति',
          'Order ID': 'ऑर्डर आईडी',
          'No Order Placed!': 'कोई आदेश नहीं दिया गया!',
          'Submit Review': 'समीक्षा सबमिट करें',
          'Size': 'आकार',
          'Quantity': 'मात्रा',
          'Price': 'मूल्य',
          'Make Payment': 'भुगतान करें',
          'No Promos Selected': 'कोई प्रोमो चयनित नहीं',
          'Pay' : 'भुगतान किया गया',
          'InvoiceID': 'चालान संख्या',
          'Phone': 'फोन',
          'User Information': 'उपयोगकर्ता जानकारी',
          'You are Unauthenticated.': 'आप प्रमाणित नहीं हैं।',
          'Please Log In.': 'कृपया लॉग इन करें।',
          'File': 'फ़ाइल',
          'Camera': 'कैमरा',
          'FAQ': 'अक्सर पूछे जाने वाले प्रश्न',
          'Terms of Service': 'सेवा की शर्तें',
          'About us': 'हमारे बारे में',
          'Rate us': 'हमें रेट करें',
          'Visit Our Website': 'हमारी वेबसाइट पर जाएं',
          'Accessibility': 'सुलभता',
          'FeedBack': 'फीडबैक',
          'Contact Support': 'सहायता से संपर्क करें',
          'Change Password': 'पासवर्ड बदलें',
          'We are sorry!': 'हमें खेद है!',
          'Something went wrong. Please try again.': 'कुछ गलत हो गया। कृपया पुन: प्रयास करें।',
          'Item': 'वस्तु',
          'Items': 'वस्तुएं',

        },
        'ar_AR': {
          //arabic
          'Awesome! Product Carted':'مذهل! المنتج في سلة التسوق',
          'Want to Continue Shopping':'أريد مواصلة التسوق',
          'Continue Shopping':'مواصلة التسوق',
          'Go to Cart':'اذهب إلى سلة التسوق',
          'Chat with Seller':"الدردشة مع البائع",
          'Chat with CustomerCare':"الدردشة مع خدمة العملاء",
          'Username or Email':'اسم المستخدم أو البريد الالكتروني',
          'Name':'اسم',
          'Privacy Policy':'سياسة الخصوصية',
          'Return Order':'أمر الإرجاع',
          'Return Reason':'سبب عودة',
          'Cancellation Reason':'سبب عودة',
          'Confirm':'يتأكد',
          'Order is being Processed to be Returned':'تتم معالجة الطلب لإعادته',
          'Go to Home':'اذهب إلى الصفحة الرئيسية',
          'Check Out Our New Deals!':'تحقق من عروضنا الجديدة!',
          'Want to Use this Promo?':'هل تريد استخدام هذا العرض الترويجي؟',
          'Are you sure want to use this promo?':'هل أنت متأكد أنك تريد استخدام هذا العرض الترويجي؟',
          'No':'لا',
          'Yes':'نعم',
          'Promos didn\'t Redeemed':'لم يتم استرداد العروض الترويجية',
          'Promos Redeemed Successfully':'تم استرداد العروض الترويجية بنجاح',
          'Ask Questions':'اسال اسئلة',
          'Select gender':'حدد نوع الجنس',
          'Male':'ذكر',
          'Female':'أنثى',
          'Others':'آحرون',
          'Enter Number':'أدخل رقم',
          'Tired of the same? Upgrade your game! Download Shopaholic and join the fashion fame.':
              'تعبت من نفسه؟ ترقية لعبتك! قم بتنزيل Shopaholic وانضم إلى شهرة الموضة.',
          'Wished Items': 'العناصر المرغوبة',
          'Spotted something you love? Wishlist it and let it know you\'re interested':
              'رصدت شيئا تحبه؟ قم بإدراجها في قائمة الرغبات وأخبرها أنك مهتم',
          'Flash Sales': 'مبيعات فلاش',
          'Lightning Deals! Don\'t blink or these hot styles will vanish faster than your chance to say "Shopaholic!" ⚡️':
              'عروض البرق! لا ترمش وإلا ستختفي هذه الأنماط الجذابة بشكل أسرع من فرصتك في قول "محبي التسوق!" ⚡️',
          'Add to Cart': 'أضف إلى السلة',
          'Found something oh-so-fine? Click "Add to Cart" and make it shine! ✨':
              'وجدت شيئا يا على ما يرام؟ انقر فوق "أضف إلى العربة" واجعلها لامعة! ✨',
          'Exciting Deals': 'عروض مثيرة',
          'Lightning speed, amazing savings! Shop Shopaholic\'s hot deals and checkout in a snap. Time to treat yourself!':
              'سرعة البرق، وفورات مذهلة! تسوق صفقات Shopaholic الساخنة وقم بالخروج في لمح البصر. الوقت لعلاج نفسك!',
          'Leave a Review': 'ترك التعليق',
          'Did this item live up to the hype? Share your thoughts and unlock exclusive Shopaholic rewards!':
              'هل هذا البند ترقى إلى مستوى الضجيج؟ شارك أفكارك واحصل على مكافآت محبي التسوق الحصرية!',
          'Hi': 'أهلاً',
          'Home': 'بيت',
          'Leaderboard': 'المتصدرين',
          'Points': 'نقاط',
          'Profile': 'حساب تعريفي',
          'Skip': 'يتخطى',
          'Done': 'منتهي',
          'Login': 'تسجيل الدخول',
          'Email': 'بريد إلكتروني',
          'Password': 'كلمة المرور',
          'Confirm Password': 'تأكيد كلمة المرور',
          'Continue': 'يكمل',
          'Create new Password?': 'إنشاء كلمة مرور جديدة',
          'Create new password': 'إنشاء كلمة مرور جديدة',
          'Confirm new password': 'تأكيد كلمة المرور الجديدة',
          'Forgot Password?': 'هل نسيت كلمة السر؟',
          'Don\'t have an account?': 'ليس لديك حساب؟',
          'Register': 'يسجل',
          'Or': 'أو',
          'Already have an account?': 'هل لديك حساب؟',
          'Language': 'لغة',
          'View All': 'عرض الكل',
          'See more': 'شاهد المزيد',
          'Search': 'يبحث',
          'Settings': 'إعدادات',
          'About Us': 'معلومات عنا',
          'LogOut': 'تسجيل خروج',
          'Log Out Account': 'تسجيل الخروج من الحساب',
          'Are you sure, you want to log out?':
              'هل أنت متأكد من أنك تريد تسجيل الخروج',
          'Categories': 'فئات',
          'Cancel': 'يلغي',
          'Ok': 'نعم',
          'Let\'s Get Started!': 'هيا بنا نبدأ',
          'Let\'s Dive into Your Account': 'دعنا نتعمق في حسابك',
          'Continue with Google': 'تواصل مع جوجل',
          'Continue with Apple': 'تواصل مع أبل',
          'Continue with Facebook': 'تواصل مع الفيسبوك',
          'Continue with Twitter': 'تواصل مع تويتر',
          'Join Shopaholic': 'انضم إلى محبي التسوق',
          'Embark on a Fashion Journey Tailored for You':
              'انطلق في رحلة أزياء مصممة خصيصًا لك',
          'User Name': 'اسم المستخدم',
          'I agree to Shopaholic': 'أوافق على شروط وأحكام محبي التسوق.',
          ' Terms & Conditions.': ' Terms & Conditions.',
          'Welcome \nBack!': 'مرحبًا بعودتك!',
          'UserName or Email': 'اسم المستخدم أو البريد الالكتروني',
          'Remember Me': 'تذكرنى',
          'We\'ve got you covered. Enter your registered email to reset your password. Will will send an OTP code to your email for the next steps.':
              'لقد حصلت على تغطيتها. أدخل بريدك الإلكتروني المسجل لإعادة تعيين كلمة المرور الخاصة بك. سوف يرسل رمز OTP إلى بريدك الإلكتروني لمعرفة الخطوات التالية.',
          'Your Registered Email': 'بريدك الإلكتروني المسجل',
          'Send OTP Code': 'إرسال رمز OTP',
          'Enter OTP Code': 'أدخل رمز OTP',
          'Please check your email inbox for a message from Shopaholic. Enter the one-time verification code bellow.':
              'يرجى التحقق من صندوق البريد الإلكتروني الخاص بك للحصول على رسالة من Shopaholic. أدخل رمز التحقق لمرة واحدة أدناه.',
          'You can resend the code in ': 'يمكنك إعادة إرسال الرمز في',
          'seconds': 'ثواني',
          'Resend Code': 'أعد إرسال الرمز',
          'Verify': 'يؤكد',
          'Secure Your Account': 'تأمين حسابك',
          'Create a new password for Shopaholic account to keep it secure. Remember to choose a strong and unique password.':
              'قم بإنشاء كلمة مرور جديدة لحساب Shopaholic لإبقائه آمنًا. تذكر أن تختار كلمة مرور قوية وفريدة من نوعها.',
          'Save': 'يحفظ',
          'You\'re All Set': 'أنت جاهز تمامًا',
          'Your Password Changed Successfully.':
              'تم تغيير كلمة المرور الخاصة بك بنجاح.',
          'Account': 'حساب',
          'Orders': 'طلبات',
          'Cart': 'عربة التسوق',
          'Wishlist': 'قائمة الرغبات',
          'Contact Us': 'اتصل بنا',
          'My Order': 'طلبي',
          'Special Offers': 'عروض خاصة',
          'We make sure you get the offer': 'نحن نتأكد من حصولك على العرض',
          'New Arrivals': 'الوافدون الجدد',
          'Flat and Heels': 'شقة والكعب',
          'Stand a chance to\nget rewarded':
              'احصل على فرصة للحصول على المكافأة',
          'Trending Products': 'المنتجات الرائجة',
          'Summer\'25 Collections': 'مجموعات صيف 25',
          'Beauty & Fashion': 'الجمال والموضة',
          'Products': 'منتجات',
          'Sort': 'نوع',
          'Filter': 'منقي',
          'Apply': 'يتقدم',
          'Material': 'مادة',
          'Variants': 'المتغيرات',
          'Color': 'الألوان',
          'Product Details': 'تفاصيل المنتج',
          'No Wished Items!': 'لا توجد عناصر مرغوبة!',
          'Checkout': 'الدفع',
          'Edit Product Variant': 'تحرير متغير المنتج',
          'Promos & Vouchers': 'العروض الترويجية والقسائم',
          'Add to Wishlist': 'أضف إلى قائمة الامنيات',
          'Wishlisted': 'تم إدراجه في قائمة الرغبات',
          'Rating & Reviews': 'التقييم والمراجعات',
          'See less': 'انظر أقل',
          'Delivery Address': 'عنوان التسليم',
          'Your Order': 'طلبك',
          'Delivery': 'توصيل',
          'Payment Methods': 'طرق الدفع',
          'Review Summary': 'ملخص المراجعة',
          'Confirm Order': 'أكد الطلب',
          'Processing Payments...': 'معالجة المدفوعات...',
          'Order Confirmed': 'تم تاكيد الطلب',
          'View Orders': 'عرض الطلبات',
          'Active': 'نشيط',
          'Completed': 'مكتمل',
          'Canceled': 'ألغيت',
          'Cancel Order': 'إلغاء الطلبات',
          'Track Order': 'ترتيب المسار',
          'Order has Arrived': 'وصل الطلب',
          'Delivery Status': 'حالة التسليم',
          'Order Details': 'تفاصيل الطلب',
          'Rate your Order': 'قيم طلبك',
          'Submit': 'يُقدِّم',
          'Promoted Products': 'المنتجات المروجة',
          'Search History': 'سجل البحث',
          'Recently Viewed': 'شوهدت مؤخرا',
          'Edit Profile': 'تعديل الملف الشخصي',
          'Account & Security': 'أمن الحساب',
          'Order History': 'تاريخ الطلب',
          'Notifications': 'إشعارات',
          'Help & Supports': 'المساعدة والدعم',
          'You may also like': 'ربما يعجبك أيضا',
          'No Product Carted!': 'لم يتم شحن أي منتج!',
          'Are you sure you want to cancel the order?':
              'هل أنت متأكد أنك تريد إلغاء الطلب؟',
          'It\'s okay to change your mind! your payment will be safely refunded.':
              'لا بأس أن تغير رأيك! سيتم رد دفعتك بأمان.',
          ' Terms & Conditions': 'البنود و الظروف',
          ' may apply.': 'قد تنطبق.',
          'No, Don\'t Cancel': 'لا، لا تقم بالإلغاء',
          'Yes, Cancel Order': 'نعم، قم بإلغاء الطلب',
          'Order Canceled Successfully!': 'تم إلغاء الطلب بنجاح',
          'Buy': 'يشتري',
          'Ends in': 'ينتهي في',
          'Have a Promo Code?': 'هل يمتلك الرمز الترويجي؟',
          'Enter Code Here': 'أدخل رمز هنا',
          'Redeem': 'يسترد',
          'Full Name': 'الاسم الكامل',
          'Phone Number': 'رقم التليفون',
          'Gender': 'جنس',
          'Date of Birth': 'تاريخ الميلاد',
          'Theme': 'سمة',
          'Sold': 'تم البيع',
          'Type': 'النوع',
          'Reset': 'إعادة تعيين',
          'Sorry': 'آسف',
          "You don't have any notification yet.": "ليس لديك أي إشعارات بعد.",
          'Back': 'رجوع',
          'No Reviews Found': 'لا توجد تقييمات',
          'No Q&A Found': 'لا توجد أسئلة وأجوبة',
          "Select Address": 'اختر العنوان',
          "No Address Selected": 'لم يتم اختيار عنوان',
          'Select Promo': 'اختر العرض',
          'Subtotal': 'المجموع الفرعي',
          'Total': 'الإجمالي',
          'Address Label': 'ملصق العنوان',
          'Phone No.': 'رقم الهاتف',
          'City': 'المدينة',
          'District': 'المنطقة',
          'Select Area': 'اختر المنطقة',
          'Address': 'العنوان',
          'Inside Dhaka': 'داخل دكا',
          'Outside Dhaka': 'خارج دكا',
          'Add Address Details': 'أضف تفاصيل العنوان',
          'Payment Gateway': 'بوابة الدفع',
          'Paid': 'مدفوع',
          'Due': 'مستحق',
          'Pending': 'قيد الانتظار',
          'Confirmed': 'مؤكد',
          'Shipped': 'جاري',
          'Delivered': 'تم التسليم',
          'Cancelled': 'ملغى',
          'Returned': 'مرتجع',
          'Rejected': 'مرفوض',
          'Shipping Charge': 'تكلفة الشحن',
          'Discount': 'خصم',
          'Tax': 'ضريبة',
          'Vat': 'ضريبة القيمة المضافة',
          'Information Details': 'تفاصيل المعلومات',
          'Purchase Date': 'تاريخ الشراء',
          'Purchase Time': 'وقت الشراء',
          'Invoice Number': 'رقم الفاتورة',
          "Generate Invoice": 'إنشاء فاتورة',
          'Order has been': 'تم الطلب',
          'Status': 'الحالة',
          'Order ID': 'معرف الطلب',
          'No Order Placed!': 'لم يتم تقديم أي طلب!',
          'Submit Review': 'أرسل التقييم',
          'Size': 'حجم',
          'Quantity': 'كمية',
          'Price': 'السعر',
          'Make Payment': 'إجراء الدفع',
          'No Promos Selected': 'لم يتم اختيار أي عروض',
          'Pay' : 'مدفوع',
          'InvoiceID': 'رقم الفاتورة',
          'Phone': 'الهاتف',
          'User Information': 'معلومات المستخدم',
          'You are Unauthenticated.': 'أنت غير مصدق.',
          'Please Log In.': 'يرجى تسجيل الدخول.',
          'File': 'ملف',
          'Camera': 'كاميرا',
          'FAQ': 'الأسئلة الشائعة',
          'Terms of Service': 'شروط الخدمة',
          'About us': 'معلومات عنا',
          'Rate us': 'قيمنا',
          'Visit Our Website': 'زيارة موقعنا',
          'Accessibility': 'إمكانية الوصول',
          'FeedBack': 'تعليقات',
          'Contact Support': 'اتصل بالدعم',
          'Change Password': 'تغيير كلمة المرور',
          'We are sorry!': 'نحن آسفون!',
          'Something went wrong. Please try again.': 'حدث خطأ ما. يرجى المحاولة مرة أخرى.',
          'Item': 'عنصر',
          'Items': 'عناصر',

        },
        'pt_PT': {
          //portugal
          'Awesome! Product Carted':'Incrível! Produto transportado',
          'Want to Continue Shopping':'Quer continuar comprando',
          'Continue Shopping':'Continue comprando',
          'Go to Cart':'Ir para o carrinho',
          'Chat with Seller':'Converse com o vendedor',
          'Chat with CustomerCare':'Converse com CustomerCare',
          'Username or Email':'Nome de usuário ou email',
          'Name':'Nome',
          'Privacy Policy':'política de Privacidade',
          'Return Order':'Pedido de devolução',
          'Return Reason':'Motivo da devolução',
          'Cancellation Reason':'Motivo do cancelamento',
          'Confirm':'confirme',
          'Order is being Processed to be Returned':'O pedido está sendo processado para ser devolvido',
          'Go to Home':'Vá para casa',
          'Check Out Our New Deals!':'Confira nossas novas ofertas!',
          'Want to Use this Promo?':'Quer usar esta promoção?',
          'Are you sure want to use this promo?':'Tem certeza de que deseja usar esta promoção?',
          'No':'Não',
          'Yes':'Sim',
          'Promos didn\'t Redeemed':'As promoções não foram resgatadas',
          'Promos Redeemed Successfully':'Promoções resgatadas com sucesso',
          'Ask Questions':'Pergunte',
          'Select gender':'Selecione o sexo',
          'Male':'Macho',
          'Female':'Fêmea',
          'Others':'Outros',
          'Enter Number':'Insira numeros',
          'Tired of the same? Upgrade your game! Download Shopaholic and join the fashion fame.':
              'Cansado do mesmo? Atualize seu jogo! Baixe Shopaholic e junte-se à fama da moda.',
          'Wished Items': 'Itens desejados',
          'Spotted something you love? Wishlist it and let it know you\'re interested':
              'Encontrou algo que você ama? Adicione-o à lista de desejos e informe que você está interessado',
          'Flash Sales': 'Vendas Relâmpago',
          'Lightning Deals! Don\'t blink or these hot styles will vanish faster than your chance to say "Shopaholic!" ⚡️':
              'Ofertas relâmpago! Não pisque ou esses estilos quentes desaparecerão mais rápido do que sua chance de dizer "Shopaholic!" ⚡️',
          'Add to Cart': 'adicionar ao carrinho',
          'Found something oh-so-fine? Click "Add to Cart" and make it shine! ✨':
              'Encontrou algo tão bom? Clique em "Adicionar ao carrinho" e faça brilhar! ✨',
          'Exciting Deals': 'Ofertas emocionantes',
          'Lightning speed, amazing savings! Shop Shopaholic\'s hot deals and checkout in a snap. Time to treat yourself!':
              'Velocidade da luz, economias incríveis! Compre as melhores ofertas do Shopaholic e finalize a compra em um piscar de olhos. É hora de se tratar!',
          'Leave a Review': 'Deixe um comentário',
          'Did this item live up to the hype? Share your thoughts and unlock exclusive Shopaholic rewards!':
              'Este item correspondeu ao hype? Compartilhe suas idéias e desbloqueie recompensas exclusivas do Shopaholic!',
          'Hi': 'Oi',
          'Home': 'Lar',
          'Skip': 'Pular',
          'Done': 'Feito',
          'Login': 'Conecte-se',
          'Email': 'E-mail',
          'Password': 'Senha',
          'Confirm Password': 'Confirme sua senha',
          'Continue': 'Continuar',
          'Create new Password?': 'Criar nova senha?',
          'Create new password': 'Criar nova senha',
          'Confirm new password': 'Confirme a nova senha',
          'Forgot Password?': 'Esqueceu sua senha?',
          'Don\'t have an account?': 'Não tem uma conta?',
          'Register': 'Registro',
          'Or': 'Ou',
          'Already have an account?': 'já tem uma conta?',
          'Language': 'Linguagem',
          'View All': 'Ver tudo',
          'See more': 'Ver mais',
          'Search': 'Procurar',
          'Settings': 'Configurações',
          'About Us': 'Sobre nós',
          'LogOut': 'Sair',
          'Log Out Account': 'Sair da conta',
          'Are you sure, you want to log out?':
              'Tem certeza de que deseja sair?',
          'Categories': 'Categorias',
          'Cancel': 'Cancelar',
          'Ok': 'OK',
          'Let\'s Get Started!': 'Vamos começar',
          'Let\'s Dive into Your Account': 'Vamos mergulhar na sua conta',
          'Continue with Google': 'Continuar com o Google',
          'Continue with Apple': 'Continuar com o Apple',
          'Continue with Facebook': 'Continuar com o Facebook',
          'Continue with Twitter': 'Continuar com o Twitter',
          'Join Shopaholic': 'Junte-se ao Shopaholic',
          'Embark on a Fashion Journey Tailored for You':
              'Embarque em uma jornada de moda feita sob medida para você',
          'User Name': 'Nome de usuário',
          'I agree to Shopaholic':
              'Eu concordo com os Termos e Condições do Shopaholic.',
          ' Terms & Conditions.': ' Terms & Conditions.',
          'Welcome \nBack!': 'Bem vindo de volta!',
          'UserName or Email': 'Nome de usuário ou email',
          'Remember Me': 'Lembre de mim',
          'We\'ve got you covered. Enter your registered email to reset your password. Will will send an OTP code to your email for the next steps.':
              'Estamos protegendo você. Digite seu e-mail cadastrado para redefinir sua senha. Will enviará um código OTP para seu e-mail para as próximas etapas.',
          'Your Registered Email': 'Seu e-mail cadastrado',
          'Send OTP Code': 'Enviar código OTP',
          'Enter OTP Code': 'Insira o código OTP',
          'Please check your email inbox for a message from Shopaholic. Enter the one-time verification code bellow.':
              'Por favor, verifique sua caixa de entrada de e-mail para ver se há uma mensagem do Shopaholic. Digite o código de verificação único abaixo.',
          'You can resend the code in ': 'Você pode reenviar o código em',
          'seconds': 'segundos',
          'Resend Code': 'Reenviar código',
          'Verify': 'Verificar',
          'Secure Your Account': 'Proteja sua conta',
          'Create a new password for Shopaholic account to keep it secure. Remember to choose a strong and unique password.':
              'Crie uma nova senha para a conta Shopaholic para mantê-la segura. Lembre-se de escolher uma senha forte e exclusiva.',
          'Save': 'Salvar',
          'You\'re All Set': 'Você está tudo pronto',
          'Your Password Changed Successfully.':
              'Sua senha foi alterada com sucesso.',
          'Account': 'Conta',
          'Orders': 'Pedidos',
          'Cart': 'Carrinho',
          'Wishlist': 'Lista de Desejos',
          'Contact Us': 'Contate-nos',
          'My Order': 'Meu pedido',
          'Special Offers': 'Ofertas especiais',
          'We make sure you get the offer':
              'Nós garantimos que você receba a oferta',
          'New Arrivals': 'Novas chegadas',
          'Flat and Heels': 'Plano e salto',
          'Stand a chance to\nget rewarded':
              'Tenha a chance de ser recompensado',
          'Trending Products': 'Produtos em alta',
          'Summer\'25 Collections': 'Coleções Verão\'25',
          'Beauty & Fashion': 'Beleza e moda',
          'Products': 'Produtos',
          'Sort': 'Organizar',
          'Filter': 'Filtro',
          'Apply': 'Aplicar',
          'Material': 'Material',
          'Variants': 'Variantes',
          'Color': 'Cores',
          'Product Details': 'Detalhes do produto',
          'No Wished Items!': 'Nenhum item desejado!',
          'Checkout': 'Confira',
          'Edit Product Variant': 'Editar variante do produto',
          'Promos & Vouchers': 'Promoções e vouchers',
          'Add to Wishlist': 'Adicionar a lista de desejos',
          'Wishlisted': 'Na lista de desejos',
          'Rating & Reviews': 'Classificação e comentários',
          'See less': 'Ver menos',
          'Delivery Address': 'Endereço de entrega',
          'Your Order': 'Seu pedido',
          'Delivery': 'Entrega',
          'Payment Methods': 'Métodos de Pagamento',
          'Review Summary': 'Resumo da revisão',
          'Confirm Order': 'Confirmar pedido',
          'Processing Payments...': 'Processando pagamentos...',
          'Order Confirmed': 'Pedido confirmado',
          'View Orders': 'Ver pedidos',
          'Active': 'Ativo',
          'Completed': 'Concluído',
          'Canceled': 'Cancelado',
          'Cancel Order': 'Cancelar pedidos',
          'Track Order': 'Acompanhar Pedido',
          'Order has Arrived': 'O pedido chegou',
          'Delivery Status': 'Status de entrega',
          'Order Details': 'detalhes do pedido',
          'Rate your Order': 'Avalie seu pedido',
          'Submit': 'Enviar',
          'Promoted Products': 'Produtos Promovidos',
          'Search History': 'Histórico de busca',
          'Recently Viewed': 'Visualizado recentemente',
          'Edit Profile': 'Editar Perfil',
          'Account & Security': 'Segurança da conta',
          'Order History': 'Histórico de pedidos',
          'Notifications': 'Notificações',
          'Help & Supports': 'Ajuda e suporte',
          'You may also like': 'você pode gostar',
          'No Product Carted!': 'Nenhum Produto Carregado!',
          'Are you sure you want to cancel the order?':
              'Tem certeza de que deseja cancelar o pedido?',
          'It\'s okay to change your mind! your payment will be safely refunded.':
              'Não há problema em mudar de ideia! seu pagamento será reembolsado com segurança.',
          ' Terms & Conditions': 'termos e Condições',
          ' may apply.': 'Pode aplicar.',
          'No, Don\'t Cancel': 'Não, não cancele',
          'Yes, Cancel Order': 'Sim, cancelar pedido',
          'Order Canceled Successfully!': 'Pedido cancelado com sucesso',
          'Buy': 'Comprar',
          'Ends in': 'Termina em',
          'Have a Promo Code?': 'Tem um código promocional?',
          'Enter Code Here': 'Entre com o código aqui',
          'Redeem': 'Resgatar',
          'Full Name': 'Nome completo',
          'Phone Number': 'Número de telefone',
          'Gender': 'Gênero',
          'Date of Birth': 'Data de nascimento',
          'Theme': 'Tema',
          'Sold': 'Vendido',
          'Type': 'Tipo',
          'Reset': 'Redefinir',
          'Sorry': 'Desculpe',
          "You don't have any notification yet.": "Você ainda não tem nenhuma notificação.",
          'Back': 'Voltar',
          'No Reviews Found': 'Nenhuma Avaliação Encontrada',
          'No Q&A Found': 'Nenhuma Pergunta e Resposta Encontrada',
          "Select Address": 'Selecione o Endereço',
          "No Address Selected": 'Nenhum Endereço Selecionado',
          'Select Promo': 'Selecione o Promo',
          'Subtotal': 'Subtotal',
          'Total': 'Total',
          'Address Label': 'Rótulo do Endereço',
          'Phone No.': 'Número de Telefone',
          'City': 'Cidade',
          'District': 'Distrito',
          'Select Area': 'Selecione a Área',
          'Address': 'Endereço',
          'Inside Dhaka': 'Dentro de Dhaka',
          'Outside Dhaka': 'Fora de Dhaka',
          'Add Address Details': 'Adicionar Detalhes do Endereço',
          'Payment Gateway': 'Gateway de Pagamento',
          'Paid': 'Pago',
          'Due': 'Devido',
          'Pending': 'Pendente',
          'Confirmed': 'Confirmado',
          'Shipped': 'Em Andamento',
          'Delivered': 'Entregue',
          'Cancelled': 'Cancelado',
          'Returned': 'Devolvido',
          'Rejected': 'Rejeitado',
          'Shipping Charge': 'Taxa de Envio',
          'Discount': 'Desconto',
          'Tax': 'Imposto',
          'Vat': 'IVA',
          'Information Details': 'Detalhes da Informação',
          'Purchase Date': 'Data da Compra',
          'Purchase Time': 'Hora da Compra',
          'Invoice Number': 'Número da Fatura',
          "Generate Invoice": 'Gerar Fatura',
          'Order has been': 'Pedido foi',
          'Status': 'Status',
          'Order ID': 'ID do Pedido',
          'No Order Placed!': 'Nenhum Pedido Feito!',
          'Submit Review': 'Enviar Avaliação',
          'Size': 'Tamanho',
          'Quantity': 'Quantidade',
          'Price': 'Preço',
          'Make Payment': 'Realizar Pagamento',
          'No Promos Selected': 'Nenhuma Promoção Selecionada',
          'Pay' : 'Pago',
          'InvoiceID': 'ID da Fatura',
          'Phone': 'Telefone',
          'User Information': 'Informações do Usuário',
          'You are Unauthenticated.': 'Você está não autenticado.',
          'Please Log In.': 'Por favor, faça o login.',

          'File': 'Arquivo',
          'Camera': 'Câmera',
          'FAQ': 'Perguntas Frequentes',
          'Terms of Service': 'Termos de Serviço',
          'About us': 'Sobre nós',
          'Rate us': 'Avalie-nos',
          'Visit Our Website': 'Visite Nosso Site',
          'Accessibility': 'Acessibilidade',
          'FeedBack': 'Feedback',
          'Contact Support': 'Contato com Suporte',
          'Change Password': 'Alterar Senha',
          'We are sorry!': 'Lamentamos!',
          'Something went wrong. Please try again.': 'Algo deu errado. Por favor, tente novamente.',
          'Item': 'Item',
          'Items': 'Itens',
        },
      };
}
